name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checar o código
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Rodar testes
      - name: Run tests
        run: npm test

      # 5. Executar SAST (exemplo com npm audit)
      - name: Run SAST scan
        run: npm audit --audit-level=high

      # 6. Rodar auditoria de licenças
      - name: License Audit
        run: npx license-checker --summary