name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      # 5. Análise de Segurança SAST (Semgrep)
      # Usamos uma action oficial para garantir que a ferramenta seja instalada corretamente.
      - name: SAST Analysis (Semgrep)
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      # 6. Auditoria de Licenças
      - name: License Audit
        run: npx license-checker --summary
